asset_dir = "assets"
exclude_assets = ["*.luau", "*.rbxm"]
write_dir = "assets"

[creator]
type = "group"
id = 1

[codegen]
output_name = "init"
typescript = false
style = "nested"
strip_extension = true
